'use client';

import { useState } from 'react';
import { useAccount } from 'wagmi';
import { ConnectButton } from '@rainbow-me/rainbowkit';
import { useRouter } from 'next/navigation';

import { useAuth } from '@/context/AuthContext';

export default function ProfilePage() {
    const { isConnected, address } = useAccount();
    const router = useRouter();

    // Global Mock Auth State
    const { isLoggedIn, userEmail, login, logout } = useAuth();

    // Local form state
    const [email, setEmail] = useState('');
    const [password, setPassword] = useState('');

    // Mock Custodial Wallet (generated by system)
    const custodialWallet = "0x777...8888";

    // Mock Wallet Binding
    const [boundWallets, setBoundWallets] = useState<string[]>([]);

    const handleLogin = (e: React.FormEvent) => {
        e.preventDefault();
        if (email && password) {
            login(email);
        }
    };

    const handleBindWallet = () => {
        if (isConnected && address && !boundWallets.includes(address)) {
            setBoundWallets([...boundWallets, address]);
            alert(`Success! Wallet ${address.slice(0, 6)}... linked to your account.`);
        }
    };

    return (
        <div className="min-h-screen bg-[var(--background)] text-white font-[family-name:var(--font-inter)] p-6">
            <header className="fixed top-0 left-0 right-0 p-4 border-b border-white/10 bg-[rgba(5,5,16,0.9)] backdrop-blur mb-10 z-50 flex justify-between items-center">
                <h1 className="text-xl font-[family-name:var(--font-orbitron)] tracking-widest text-[var(--neon-cyan)]">
                    MEMBER CENTER
                </h1>
                <button onClick={() => router.push('/library')} className="font-mono text-xs hover:text-[var(--neon-cyan)]">
                    &larr; BACK TO LIBRARY
                </button>
            </header>

            <div className="max-w-4xl mx-auto mt-20">
                {!isLoggedIn ? (
                    // 1. LOGIN FORM (Web2 Style)
                    <div className="max-w-md mx-auto p-8 border border-[var(--glass-border)] bg-[var(--glass-bg)] rounded-2xl shadow-[0_0_50px_rgba(0,0,0,0.5)]">
                        <h2 className="text-2xl font-[family-name:var(--font-orbitron)] mb-6 text-center">WELCOME BACK</h2>
                        <form onSubmit={handleLogin} className="space-y-4">
                            <div>
                                <label className="block text-xs font-mono text-gray-400 mb-1">EMAIL</label>
                                <input
                                    type="email"
                                    value={email}
                                    onChange={e => setEmail(e.target.value)}
                                    placeholder="user@example.com"
                                    className="w-full bg-black/40 border border-gray-700 rounded p-3 text-white focus:border-[var(--neon-cyan)] outline-none transition-colors"
                                />
                            </div>
                            <div>
                                <label className="block text-xs font-mono text-gray-400 mb-1">PASSWORD</label>
                                <input
                                    type="password"
                                    value={password}
                                    onChange={e => setPassword(e.target.value)}
                                    placeholder="••••••••"
                                    className="w-full bg-black/40 border border-gray-700 rounded p-3 text-white focus:border-[var(--neon-cyan)] outline-none transition-colors"
                                />
                            </div>
                            <button className="w-full py-3 bg-[var(--neon-cyan)] text-black font-bold font-[family-name:var(--font-orbitron)] rounded hover:bg-[var(--neon-cyan)]/80 transition-all shadow-[0_0_20px_rgba(0,243,255,0.3)] mt-4">
                                LOGIN
                            </button>
                        </form>
                        <div className="mt-6 text-center">
                            <p className="text-xs text-gray-500 font-mono">Don't have an account? <span className="text-[var(--neon-pink)] cursor-pointer hover:underline">Register (Auto-Create Wallet)</span></p>
                        </div>
                    </div>
                ) : (
                    // 2. PROFILE DASHBOARD (Web2.5 Style)
                    <div className="space-y-8">

                        {/* User Info Card */}
                        <div className="p-8 border border-[var(--glass-border)] bg-[var(--glass-bg)] rounded-2xl relative overflow-hidden group">
                            <div className="relative z-10 flex items-start justify-between">
                                <div>
                                    <h2 className="text-3xl font-[family-name:var(--font-orbitron)] text-white mb-2">{userEmail?.split('@')[0]}</h2>
                                    <p className="text-gray-400 font-mono text-sm">{userEmail}</p>
                                    <div className="mt-4 flex gap-3">
                                        <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-[var(--neon-purple)]/20 border border-[var(--neon-purple)]/50 text-[var(--neon-purple)] text-xs font-mono">
                                            <span>★ PREMIUM MEMBER</span>
                                        </div>
                                        {/* Mock Edit Profile */}
                                        <button onClick={() => alert("Edit Profile Feature Coming Soon")} className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-white/10 border border-white/20 text-gray-300 text-xs font-mono hover:bg-white/20 transition-colors">
                                            <span>✎ EDIT PROFILE</span>
                                        </button>
                                    </div>
                                    <button onClick={logout} className="mt-4 text-xs text-red-400 hover:text-red-300 underline block">LOGOUT</button>
                                </div>
                                <div className="w-16 h-16 rounded-full bg-gradient-to-br from-[var(--neon-cyan)] to-[var(--neon-purple)] flex items-center justify-center text-2xl font-bold text-black border-2 border-white">
                                    {userEmail?.[0].toUpperCase()}
                                </div>
                            </div>
                            {/* Decoration */}
                            <div className="absolute -right-10 -top-10 w-64 h-64 bg-[var(--neon-purple)]/20 blur-[100px] rounded-full pointer-events-none"></div>
                        </div>

                        {/* NEW: MY INVENTORY (v1.6) */}
                        <div className="p-6 border border-gray-700 bg-black/40 rounded-xl">
                            <h3 className="text-lg font-[family-name:var(--font-orbitron)] mb-6 flex items-center gap-2 text-[var(--neon-cyan)]">
                                <span>📚</span> MY INVENTORY
                            </h3>

                            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                                {/* Mock Book Item 1 */}
                                <div className="flex items-center gap-4 bg-white/5 p-4 rounded-lg border border-white/10 hover:border-[var(--neon-cyan)]/50 transition-colors cursor-pointer" onClick={() => router.push('/read/1')}>
                                    <div className="w-12 h-16 bg-gray-700 rounded flex items-center justify-center text-xs text-gray-400 font-mono">
                                        COVER
                                    </div>
                                    <div className="flex-1">
                                        <h4 className="font-bold text-white text-sm font-[family-name:var(--font-orbitron)]">The Future of Web3</h4>
                                        <p className="text-xs text-gray-400 font-mono">ID: #1 | Tier: Early Bird</p>
                                    </div>
                                    <div className="bg-[var(--neon-cyan)]/20 text-[var(--neon-cyan)] px-3 py-1 rounded font-mono text-xs font-bold">
                                        x1
                                    </div>
                                </div>

                                {/* Mock Book Item 2 */}
                                <div className="flex items-center gap-4 bg-white/5 p-4 rounded-lg border border-white/10 hover:border-[var(--neon-cyan)]/50 transition-colors cursor-pointer" onClick={() => router.push('/read/4')}>
                                    <div className="w-12 h-16 bg-gray-700 rounded flex items-center justify-center text-xs text-gray-400 font-mono">
                                        COVER
                                    </div>
                                    <div className="flex-1">
                                        <h4 className="font-bold text-white text-sm font-[family-name:var(--font-orbitron)]">DeFi for Dummies</h4>
                                        <p className="text-xs text-gray-400 font-mono">ID: #4 | Tier: Standard</p>
                                    </div>
                                    <div className="bg-[var(--neon-cyan)]/20 text-[var(--neon-cyan)] px-3 py-1 rounded font-mono text-xs font-bold">
                                        x2
                                    </div>
                                </div>
                            </div>
                        </div>

                        {/* WALLET MANAGEMENT (The "Hybrid" Part) */}
                        <div className="grid grid-cols-1 md:grid-cols-2 gap-8">

                            {/* Left: Custodial Wallet */}
                            <div className="p-6 border border-gray-700 bg-black/40 rounded-xl">
                                <h3 className="text-lg font-[family-name:var(--font-orbitron)] mb-4 flex items-center gap-2">
                                    <span className="w-2 h-2 bg-[var(--neon-cyan)] rounded-full animate-pulse"></span>
                                    SYSTEM WALLET
                                </h3>
                                <p className="text-gray-400 text-xs mb-4">
                                    This wallet was automatically created for you to store your purchased books. You don't need to manage private keys.
                                </p>
                                <div className="bg-black border border-gray-800 p-3 rounded font-mono text-xs text-gray-300 break-all mb-4">
                                    {custodialWallet}
                                </div>
                                <button className="text-xs text-[var(--neon-cyan)] hover:underline">View on PolygonScan &rarr;</button>
                            </div>

                            {/* Right: External Bindings */}
                            <div className="p-6 border border-gray-700 bg-black/40 rounded-xl">
                                <h3 className="text-lg font-[family-name:var(--font-orbitron)] mb-4 text-[var(--neon-pink)]">
                                    LINKED WALLETS
                                </h3>
                                <p className="text-gray-400 text-xs mb-4">
                                    Connect your personal Web3 wallets to sync assets to your library.
                                </p>

                                {boundWallets.length > 0 && (
                                    <ul className="space-y-2 mb-4">
                                        {boundWallets.map(w => (
                                            <li key={w} className="flex justify-between items-center bg-white/5 p-2 rounded border border-white/10">
                                                <span className="font-mono text-xs">{w.slice(0, 6)}...{w.slice(-4)}</span>
                                                <span className="text-[10px] bg-green-900 text-green-300 px-2 py-0.5 rounded">CONNECTED</span>
                                            </li>
                                        ))}
                                    </ul>
                                )}

                                {isConnected ? (
                                    boundWallets.includes(address || '') ? (
                                        <div className="text-center py-2 text-gray-500 text-xs">Current wallet already linked</div>
                                    ) : (
                                        <button
                                            onClick={handleBindWallet}
                                            className="w-full py-2 border border-[var(--neon-pink)] text-[var(--neon-pink)] hover:bg-[var(--neon-pink)] hover:text-black transition text-xs font-bold font-mono uppercase tracking-wider rounded"
                                        >
                                            Link Current Wallet
                                        </button>
                                    )
                                ) : (
                                    <div className="flex flex-col gap-2">
                                        <ConnectButton label="Connect External Wallet" />
                                        <p className="text-[10px] text-gray-500 text-center mt-1">Select 'MetaMask' or others to link</p>
                                    </div>
                                )}
                            </div>

                        </div>
                    </div>
                )}
            </div>
        </div>
    );
}
